### PR TITLE
autodetect terminal height for --limit

### LINKED ISSUE #2: autodetect terminal height for --limit
set the `-l` flag to the value of the current terminal height automatically

allow `-l` to override this autodetection

use `tput` or `stty` to determine the terminal dimensions, use whichever is available, and default to none if the system doesn't have these programs

### PR DESCRIPTION
**Pull request by theRemix**
attempted to use `tput` || `stty` however, `stty` doesn't work in the child process exec 

```
stty: 'standard input': Inappropriate ioctl for device
```

so this pr is just relying on `tput`

resolves #2

### CODE REVIEW

**Review by epilande — COMMENTED** [review]
Nice!! I need this feature! 

Though `tput` in node doesn't seem to be working correctly.. 🤔 

Running `$ tput lines` directly from my shell outputs the correct number, though I'm not sure why `tput lines` in a node environment always return `24`. 😕 

Here's a screenshot of the issue:
image

**Comment by epilande** [comment]
Hmm looking at the docs for node `TTY` https://nodejs.org/api/tty.html#tty_class_tty_writestream

`process.stdout.getWindowSize()` seems to return the correct terminal `[cols, rows]`. 

image

**Comment by theRemix** [comment]
@epilande didn't know that existed! much better!

https://github.com/epilande/yex/pull/3/files#diff-2cce40143051e25f811b56c79d619bf5R57

**Review by epilande — APPROVED** [review]
Tanks!!!! 🏅

**Pull request merged**
